#!/usr/bin/env bash
# Block writes to generated / build-artifact paths.
# Blocks on PreToolUse for Edit|Write|MultiEdit.

file_path=$(jq -r '.tool_input.file_path // empty')
[[ -z "$file_path" ]] && exit 0

case "$file_path" in
  */.build/*|*/.swiftpm/*|*/NotchyPrompter.app/Contents/*|*/Package.resolved)
    echo "Refusing to edit generated/build artifact: $file_path" >&2
    echo "If you truly need this, the file is regenerated by ./build.sh or SwiftPM." >&2
    exit 2
    ;;
esac

exit 0
